services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app

    image: fama-page-app
    container_name: fama_app
    restart: unless-stopped
    working_dir: /var/www/html

    env_file:
      - .env

    volumes:
      - ./storage:/var/www/html/storage

    depends_on:
      - postgres
      - redis

    networks:
      - fama

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx

    image: fama-page-nginx
    container_name: fama_nginx
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./storage/app/public:/var/www/html/storage/app/public:ro
      - ./storage/app/generated:/var/www/html/storage/app/generated:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

    depends_on:
      - app

    networks:
      - fama

  postgres:
    image: postgres:16
    container_name: fama_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - fama

  redis:
    image: redis:7-alpine
    container_name: fama_redis
    restart: unless-stopped

    networks:
      - fama

volumes:
  postgres_data:
    name: fama-page_postgres_data

networks:
  fama:
    name: fama-page_fama
    driver: bridge
